// export const driveResult = [
//   {
//     deferrals: '96',
//     qns: '48',
//     walkouts: '48',
//     void: '0',
//     projection: '11',
//     registered: '10',
//     performed: '6',
//     actual: '2',
//     pa: '18.18',
//     appointment: '4',
//     oef: null,
//     ftd: '96',
//     noofshifts: '2',
//     status: 'Complete',
//     date: '2023-10-22T00:00:00.000Z',
//     driveid: '148',
//   },
//   {
//     deferrals: '8',
//     qns: '4',
//     walkouts: '4',
//     void: '0',
//     projection: '11',
//     registered: '5',
//     performed: '3',
//     actual: '1',
//     pa: '9.09',
//     appointment: '2',
//     oef: null,
//     ftd: '8',
//     noofshifts: '1',
//     status: 'Complete',
//     date: '2023-10-21T00:00:00.000Z',
//     driveid: '147',
//   },
//   {
//     deferrals: '8',
//     qns: '4',
//     walkouts: '4',
//     void: '0',
//     projection: '11',
//     registered: '5',
//     performed: '3',
//     actual: '1',
//     pa: '9.09',
//     appointment: '2',
//     oef: null,
//     ftd: '8',
//     noofshifts: '1',
//     status: 'Complete',
//     date: '2023-10-09T00:00:00.000Z',
//     driveid: '146',
//   },
//   {
//     deferrals: '16',
//     qns: '8',
//     walkouts: '8',
//     void: '0',
//     projection: '11',
//     registered: '5',
//     performed: '3',
//     actual: '1',
//     pa: '9.09',
//     appointment: '2',
//     oef: null,
//     ftd: '16',
//     noofshifts: '1',
//     status: 'Complete',
//     date: '2023-10-08T00:00:00.000Z',
//     driveid: '145',
//   },
//   {
//     deferrals: '0',
//     qns: '0',
//     walkouts: '0',
//     void: '0',
//     projection: '89',
//     registered: '0',
//     performed: '0',
//     actual: '0',
//     pa: '0.00',
//     appointment: '0',
//     oef: null,
//     ftd: '0',
//     noofshifts: '1',
//     status: 'Complete',
//     date: '2023-10-07T00:00:00.000Z',
//     driveid: '143',
//   },
// ];
// export const kpiDataResult = [
//   {
//     accounts_id: '180',
//     drives: {
//       id: 128,
//       date: '2023-10-01',
//       oef_products: null,
//       oef_procedures: null,
//       operation_status: {
//         id: 68,
//         name: 'Complete',
//         description: 'Demo',
//         chip_color: 'Green',
//       },
//       shifts: [
//         {
//           shiftable_type: 'drives',
//           start_time: '2023-10-01T09:00:00.001',
//           end_time: '2023-10-01T13:00:00.001',
//           shift_slots: [
//             {
//               shift_id: 70,
//               procedure_type_id: 1,
//               start_time: '2023-10-01T09:00:00.001',
//               end_time: '2023-10-01T10:00:00.001',
//             },
//           ],
//           projections: [
//             {
//               procedure_type_id: 67,
//               staff_setup_id: 1,
//               product_yield: 45,
//               procedure_type_qty: 10,
//               donor_donations: null,
//               procedure_type: {
//                 id: 67,
//                 name: 'Type BC01',
//                 short_description: 'TPB01',
//                 description: 'Type',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 12,
//                 is_generate_online_appointments: false,
//                 is_active: true,
//               },
//             },
//           ],
//         },
//       ],
//       donor_donations: [
//         {
//           id: 1,
//           donation_type: 4,
//           donation_date: null,
//           donation_status: 4,
//           drive_id: 128,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 64,
//           donation_type: 1,
//           donation_date: '2023-06-12',
//           donation_status: 1,
//           drive_id: 128,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 65,
//           donation_type: 9,
//           donation_date: '2023-04-12',
//           donation_status: 3,
//           drive_id: 128,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 2,
//           donation_type: 8,
//           donation_date: null,
//           donation_status: 5,
//           drive_id: 128,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 3,
//           donation_type: 8,
//           donation_date: '2023-04-12',
//           donation_status: 7,
//           drive_id: 128,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//       ],
//       appointment_count: 2,
//       donor_appointments: [
//         {
//           id: 1,
//           appointmentable_id: 128,
//           appointmentable_type: 'drives',
//           donor_id: 1,
//           slot_id: 1,
//           procedure_type_id: 34,
//           status: '3',
//           slot: {
//             shift_id: 70,
//             procedure_type_id: 1,
//             start_time: '2023-10-01T09:00:00.001',
//             end_time: '2023-10-01T10:00:00.001',
//           },
//         },
//         {
//           id: 2,
//           appointmentable_id: 128,
//           appointmentable_type: 'drives',
//           donor_id: 2,
//           slot_id: 1,
//           procedure_type_id: 35,
//           status: '2',
//           slot: {
//             shift_id: 70,
//             procedure_type_id: 1,
//             start_time: '2023-10-01T09:00:00.001',
//             end_time: '2023-10-01T10:00:00.001',
//           },
//         },
//       ],
//     },
//   },
//   {
//     accounts_id: '180',
//     drives: {
//       id: 135,
//       date: '2023-10-07',
//       oef_products: null,
//       oef_procedures: null,
//       operation_status: {
//         id: 68,
//         name: 'Complete',
//         description: 'Demo',
//         chip_color: 'Green',
//       },
//       shifts: [
//         {
//           shiftable_type: 'drives',
//           start_time: '2023-10-07T08:00:00',
//           end_time: '2023-10-07T14:00:00',
//           shift_slots: [
//             {
//               shift_id: 76,
//               procedure_type_id: 69,
//               start_time: '2023-10-07T08:00:00',
//               end_time: '2023-10-07T09:00:00',
//             },
//           ],
//           projections: [
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 6,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 135,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 6,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 135,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//           ],
//         },
//       ],
//       donor_donations: [
//         {
//           id: 4,
//           donation_type: 1,
//           donation_date: '2023-06-12',
//           donation_status: 1,
//           drive_id: 135,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 5,
//           donation_type: 9,
//           donation_date: '2023-04-12',
//           donation_status: 3,
//           drive_id: 135,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 6,
//           donation_type: 4,
//           donation_date: null,
//           donation_status: 4,
//           drive_id: 135,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 7,
//           donation_type: 8,
//           donation_date: null,
//           donation_status: 5,
//           drive_id: 135,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 8,
//           donation_type: 8,
//           donation_date: '2023-04-12',
//           donation_status: 7,
//           drive_id: 135,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//       ],
//       appointment_count: 2,
//       donor_appointments: [
//         {
//           id: 4,
//           appointmentable_id: 135,
//           appointmentable_type: 'drives',
//           donor_id: 2,
//           slot_id: 2,
//           procedure_type_id: 35,
//           status: '4',
//           slot: {
//             shift_id: 76,
//             procedure_type_id: 69,
//             start_time: '2023-10-07T08:00:00',
//             end_time: '2023-10-07T09:00:00',
//           },
//         },
//         {
//           id: 3,
//           appointmentable_id: 135,
//           appointmentable_type: 'drives',
//           donor_id: 1,
//           slot_id: 2,
//           procedure_type_id: 67,
//           status: '1',
//           slot: {
//             shift_id: 76,
//             procedure_type_id: 69,
//             start_time: '2023-10-07T08:00:00',
//             end_time: '2023-10-07T09:00:00',
//           },
//         },
//       ],
//     },
//   },
//   {
//     accounts_id: '180',
//     drives: {
//       id: 145,
//       date: '2023-10-08',
//       oef_products: null,
//       oef_procedures: null,
//       operation_status: {
//         id: 68,
//         name: 'Complete',
//         description: 'Demo',
//         chip_color: 'Green',
//       },
//       shifts: [
//         {
//           shiftable_type: 'drives',
//           start_time: '2023-10-08T08:00:00',
//           end_time: '2023-10-08T14:00:00',
//           shift_slots: [
//             {
//               shift_id: 96,
//               procedure_type_id: 69,
//               start_time: '2023-10-08T08:00:00',
//               end_time: '2023-10-08T09:00:00',
//             },
//           ],
//           projections: [
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 90,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 145,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 90,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 145,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 90,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 145,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 90,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 145,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//           ],
//         },
//       ],
//       donor_donations: [
//         {
//           id: 88,
//           donation_type: 1,
//           donation_date: '2023-06-12',
//           donation_status: 1,
//           drive_id: 145,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 89,
//           donation_type: 9,
//           donation_date: '2023-04-12',
//           donation_status: 3,
//           drive_id: 145,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 90,
//           donation_type: 4,
//           donation_date: null,
//           donation_status: 4,
//           drive_id: 145,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 91,
//           donation_type: 8,
//           donation_date: null,
//           donation_status: 5,
//           drive_id: 145,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 92,
//           donation_type: 8,
//           donation_date: '2023-04-12',
//           donation_status: 7,
//           drive_id: 145,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//       ],
//       appointment_count: 2,
//       donor_appointments: [
//         {
//           id: 41,
//           appointmentable_id: 145,
//           appointmentable_type: 'drives',
//           donor_id: 2,
//           slot_id: 30,
//           procedure_type_id: 35,
//           status: '4',
//           slot: {
//             shift_id: 96,
//             procedure_type_id: 69,
//             start_time: '2023-10-08T08:00:00',
//             end_time: '2023-10-08T09:00:00',
//           },
//         },
//         {
//           id: 42,
//           appointmentable_id: 145,
//           appointmentable_type: 'drives',
//           donor_id: 1,
//           slot_id: 30,
//           procedure_type_id: 67,
//           status: '1',
//           slot: {
//             shift_id: 96,
//             procedure_type_id: 69,
//             start_time: '2023-10-08T08:00:00',
//             end_time: '2023-10-08T09:00:00',
//           },
//         },
//       ],
//     },
//   },
//   {
//     accounts_id: '180',
//     drives: {
//       id: 146,
//       date: '2023-10-09',
//       oef_products: null,
//       oef_procedures: null,
//       operation_status: {
//         id: 68,
//         name: 'Complete',
//         description: 'Demo',
//         chip_color: 'Green',
//       },
//       shifts: [
//         {
//           shiftable_type: 'drives',
//           start_time: '2023-10-09T08:00:00',
//           end_time: '2023-10-09T14:00:00',
//           shift_slots: [
//             {
//               shift_id: 97,
//               procedure_type_id: 69,
//               start_time: '2023-10-09T08:00:00',
//               end_time: '2023-10-09T09:00:00',
//             },
//           ],
//           projections: [
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 95,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 146,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 95,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 146,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//           ],
//         },
//       ],
//       donor_donations: [
//         {
//           id: 93,
//           donation_type: 1,
//           donation_date: '2023-06-12',
//           donation_status: 1,
//           drive_id: 146,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 94,
//           donation_type: 9,
//           donation_date: '2023-04-12',
//           donation_status: 3,
//           drive_id: 146,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 95,
//           donation_type: 4,
//           donation_date: null,
//           donation_status: 4,
//           drive_id: 146,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 96,
//           donation_type: 8,
//           donation_date: null,
//           donation_status: 5,
//           drive_id: 146,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 97,
//           donation_type: 8,
//           donation_date: '2023-04-12',
//           donation_status: 7,
//           drive_id: 146,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//       ],
//       appointment_count: 2,
//       donor_appointments: [
//         {
//           id: 43,
//           appointmentable_id: 146,
//           appointmentable_type: 'drives',
//           donor_id: 2,
//           slot_id: 30,
//           procedure_type_id: 35,
//           status: '4',
//           slot: {
//             shift_id: 96,
//             procedure_type_id: 69,
//             start_time: '2023-10-08T08:00:00',
//             end_time: '2023-10-08T09:00:00',
//           },
//         },
//         {
//           id: 44,
//           appointmentable_id: 146,
//           appointmentable_type: 'drives',
//           donor_id: 1,
//           slot_id: 30,
//           procedure_type_id: 67,
//           status: '1',
//           slot: {
//             shift_id: 96,
//             procedure_type_id: 69,
//             start_time: '2023-10-08T08:00:00',
//             end_time: '2023-10-08T09:00:00',
//           },
//         },
//       ],
//     },
//   },
// ];
// export const getDriveDetails = [
//   {
//     accounts_id: '180',
//     drives: {
//       id: 148,
//       date: '2023-10-22',
//       oef_products: null,
//       oef_procedures: null,
//       operation_status: {
//         id: 68,
//         name: 'Complete',
//         description: 'Demo',
//         chip_color: 'Green',
//       },
//       shifts: [
//         {
//           shiftable_type: 'drives',
//           start_time: '2023-10-22T08:00:00',
//           end_time: '2023-10-22T14:00:00',
//           shift_slots: [
//             {
//               shift_id: 99,
//               procedure_type_id: 69,
//               start_time: '2023-10-22T08:00:00',
//               end_time: '2023-10-22T09:00:00',
//             },
//           ],
//           projections: [
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 105,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//                 {
//                   id: 110,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 105,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//                 {
//                   id: 110,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//           ],
//         },
//         {
//           shiftable_type: 'drives',
//           start_time: '2023-10-23T08:00:00',
//           end_time: '2023-10-23T14:00:00',
//           shift_slots: [
//             {
//               shift_id: 100,
//               procedure_type_id: 69,
//               start_time: '2023-10-23T08:00:00',
//               end_time: '2023-10-23T09:00:00',
//             },
//           ],
//           projections: [
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 105,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//                 {
//                   id: 110,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 105,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//                 {
//                   id: 110,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 105,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//                 {
//                   id: 110,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//             {
//               procedure_type_id: 4,
//               staff_setup_id: 1,
//               product_yield: 10,
//               procedure_type_qty: 11,
//               donor_donations: [
//                 {
//                   id: 105,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//                 {
//                   id: 110,
//                   donation_type: 4,
//                   donation_date: null,
//                   donation_status: 4,
//                   drive_id: 148,
//                   next_eligibility_date: '2023-11-02',
//                   donation_ytd: 1,
//                   donation_ltd: 1,
//                   donation_last_year: 1,
//                   points: 1,
//                   is_archived: false,
//                 },
//               ],
//               procedure_type: {
//                 id: 4,
//                 name: 'Nell Simon',
//                 short_description: 'Magnam impedit dese',
//                 description: 'Vitae quidem non vol',
//                 is_goal_type: true,
//                 is_archive: false,
//                 products: [
//                   {
//                     id: 68,
//                     name: 'Plasma',
//                     description: 'Plasma',
//                   },
//                 ],
//                 procedure_duration: 20,
//                 is_generate_online_appointments: true,
//                 is_active: true,
//               },
//             },
//           ],
//         },
//       ],
//       donor_donations: [
//         {
//           id: 103,
//           donation_type: 1,
//           donation_date: '2023-06-12',
//           donation_status: 1,
//           drive_id: 148,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 104,
//           donation_type: 9,
//           donation_date: '2023-04-12',
//           donation_status: 3,
//           drive_id: 148,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 105,
//           donation_type: 4,
//           donation_date: null,
//           donation_status: 4,
//           drive_id: 148,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 106,
//           donation_type: 8,
//           donation_date: null,
//           donation_status: 5,
//           drive_id: 148,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 107,
//           donation_type: 8,
//           donation_date: '2023-04-12',
//           donation_status: 7,
//           drive_id: 148,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 108,
//           donation_type: 1,
//           donation_date: '2023-06-12',
//           donation_status: 1,
//           drive_id: 148,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 109,
//           donation_type: 9,
//           donation_date: '2023-04-12',
//           donation_status: 3,
//           drive_id: 148,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 110,
//           donation_type: 4,
//           donation_date: null,
//           donation_status: 4,
//           drive_id: 148,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 111,
//           donation_type: 8,
//           donation_date: null,
//           donation_status: 5,
//           drive_id: 148,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//         {
//           id: 112,
//           donation_type: 8,
//           donation_date: '2023-04-12',
//           donation_status: 7,
//           drive_id: 148,
//           next_eligibility_date: '2023-11-02',
//           donation_ytd: 1,
//           donation_ltd: 1,
//           donation_last_year: 1,
//           points: 1,
//           is_archived: false,
//         },
//       ],
//       appointment_count: 4,
//       donor_appointments: [
//         {
//           id: 47,
//           appointmentable_id: 148,
//           appointmentable_type: 'drives',
//           donor_id: 2,
//           slot_id: 30,
//           procedure_type_id: 35,
//           status: '4',
//           slot: {
//             shift_id: 96,
//             procedure_type_id: 69,
//             start_time: '2023-10-08T08:00:00',
//             end_time: '2023-10-08T09:00:00',
//           },
//         },
//         {
//           id: 48,
//           appointmentable_id: 148,
//           appointmentable_type: 'drives',
//           donor_id: 1,
//           slot_id: 30,
//           procedure_type_id: 67,
//           status: '1',
//           slot: {
//             shift_id: 96,
//             procedure_type_id: 69,
//             start_time: '2023-10-08T08:00:00',
//             end_time: '2023-10-08T09:00:00',
//           },
//         },
//         {
//           id: 49,
//           appointmentable_id: 148,
//           appointmentable_type: 'drives',
//           donor_id: 2,
//           slot_id: 30,
//           procedure_type_id: 35,
//           status: '4',
//           slot: {
//             shift_id: 96,
//             procedure_type_id: 69,
//             start_time: '2023-10-08T08:00:00',
//             end_time: '2023-10-08T09:00:00',
//           },
//         },
//         {
//           id: 50,
//           appointmentable_id: 148,
//           appointmentable_type: 'drives',
//           donor_id: 1,
//           slot_id: 30,
//           procedure_type_id: 67,
//           status: '1',
//           slot: {
//             shift_id: 96,
//             procedure_type_id: 69,
//             start_time: '2023-10-08T08:00:00',
//             end_time: '2023-10-08T09:00:00',
//           },
//         },
//       ],
//     },
//   },
// ];
