#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "************************************ Running Lint Please Wait ************************************"
yarn --silent --version >/dev/null 2>&1 && yarn run lint
